author: phil hofmann
summary: generate models and their associations from uml diagrams
homepage: http://branch14.org/modeldrivenrails/
plugin: http://github.com/branch14/modeldrivenrails/tree/master
license: MIT
version: 0.2
rails_version: 1.1.2+
